version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: on-failure
    ports:
      - "8000:80"
    env_file:
      - .env
    depends_on:
      - db
  db:
    image: "postgres:11.3"
    restart: always
    ports:
      - 54320:5432
    env_file: .env
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: {}
